language: ruby
before_install:
  - rvm install 3.0.1
  - rvm 3.0.1 --default
  - nvm install 16
  - nvm use 16
cache:
  - bundler
  - yarn
services:
  - postgresql
before_script:
  - bundle install --jobs=3 --retry=3
  - yarn
  - bundle exec rake db:create
  - bundle exec rake db:migrate